
# Configuration
# -------------
# These macros may be overriden by config.mk, which is generated by the
# ./configure script. Use that if you want to customize them.

prefix  = /usr/local
bindir  = $(prefix)/bin
datadir = $(prefix)/share

CFLAGS     = -std=c11 -pedantic -Wall -Wextra -O2 -g
LIBS       =
SDL2_CFLAGS = `pkg-config sdl2 --cflags`
SDL2_LIBS   = `pkg-config sdl2 --libs`

INSTALL = install
INSTALL_PROGRAM = $(INSTALL)
INSTALL_DATA    = $(INSTALL) -m 644

-include config.mk


# Standard targets
# ----------------

all: xjump

clean:
	rm -rf ./*.o xjump

distclean: clean
	rm -rf config.h config.mk

install: all
	$(INSTALL_PROGRAM) -D xjump $(DESTDIR)$(bindir)/xjump
	$(INSTALL_DATA) -D images/ui-font.bmp         $(DESTDIR)$(datadir)/xjump/ui-font.bmp
	$(INSTALL_DATA) -D images/theme-jumpnbump.bmp $(DESTDIR)$(datadir)/xjump/theme-jumpnbump.bmp

uninstall:
	rm -rf $(DESTDIR)$(bindir)/xjump
	rm -rf $(DESTDIR)$(datadir)/xjump

options:
	@echo prefix  = $(prefix)
	@echo bindir  = $(bindir)
	@echo datadir = $(datadir)
	@echo compiler flags = $(CPPFLAGS) $(SDL2_CFLAGS) $(CFLAGS)
	@echo linker flags   = $(LDFLAGS) $(SDL2_LIBS) $(LIBS)

.PHONY: all clean distclean install uninstall options


# Compilation
# -----------

xjump: main.o
	$(CC) $(LDFLAGS) $< $(SDL2_LIBS) $(LIBS) -o $@

main.o: main.c config.h
	$(CC) $(CPPFLAGS) $(SDL2_CFLAGS) $(CFLAGS) -c $< -o $@

config.h: config.mk
	@echo -n '' > $@
	@echo '// This file was automatically generated by ./configure' >> $@
	@echo '// Do not edit by hand' >> $@
	@echo '#define XJUMP_VERSION "3.0"'        >> $@
	@echo '#define XJUMP_DATADIR "$(datadir)"' >> $@
