
# Configuration
# -------------
# If you want to override these variables, the recommended way is via the
# configure script. That way, everything gets recompiled automatically.

CFLAGS = -std=c17 -pedantic -Wall -Wextra -O2 -g

INSTALL = install
INSTALL_PROGRAM = $(INSTALL)
INSTALL_DATA    = $(INSTALL) -m 644

# Generated by ./configure
include config.mk

# Standard targets
# ----------------

all: xjump misc/xjump.6.gz

clean:
	rm -rf ./*.o xjump config.h misc/xjump.6.gz

distclean: clean
	rm -rf config.mk

install:
	$(INSTALL_PROGRAM) -D xjump $(DESTDIR)$(bindir)/xjump
	$(INSTALL_DATA) -D data/font-hs.bmp          $(DESTDIR)$(datadir)/xjump/font-hs.bmp
	$(INSTALL_DATA) -D data/font-ui.bmp          $(DESTDIR)$(datadir)/xjump/font-ui.bmp
	$(INSTALL_DATA) -D data/themes/classic.bmp   $(DESTDIR)$(datadir)/xjump/themes/classic.bmp
	$(INSTALL_DATA) -D data/themes/ion.bmp       $(DESTDIR)$(datadir)/xjump/themes/ion.bmp
	$(INSTALL_DATA) -D data/themes/jumpnbump.bmp $(DESTDIR)$(datadir)/xjump/themes/jumpnbump.bmp
	$(INSTALL_DATA) -D misc/xjump.6.gz           $(DESTDIR)$(datadir)/man/man6/xjump.6.gz
	$(INSTALL_DATA) -D misc/xjump.desktop        $(DESTDIR)$(datadir)/applications/$(app_id).desktop
	$(INSTALL_DATA) -D misc/xjump.metainfo.xml   $(DESTDIR)$(datadir)/metainfo/$(app_id).metainfo.xml
	$(INSTALL_DATA) -D misc/xjump.svg            $(DESTDIR)$(datadir)/icons/hicolor/scalable/apps/$(app_id).svg

uninstall:
	rm -rf $(DESTDIR)$(bindir)/xjump
	rm -rf $(DESTDIR)$(datadir)/xjump
	rm -rf $(DESTDIR)$(datadir)/man/man6/xjump.6.gz
	rm -rf $(DESTDIR)$(datadir)/applications/$(app_id).desktop
	rm -rf $(DESTDIR)$(datadir)/metainfo/$(app_id).metainfo.xml
	rm -rf $(DESTDIR)$(datadir)/icons/hicolor/scalable/apps/$(app_id).svg

.PHONY: all clean distclean install uninstall


# Compilation
# -----------

xjump: xjump.o
	$(CC) $(LDFLAGS) $< $(SDL_LIBS) $(LIBS) -o $@

xjump.o: xjump.c config.h
	$(CC) $(CPPFLAGS) $(SDL_CFLAGS) $(CFLAGS) -c $< -o $@

config.h: config.mk
	@printf "%s" "Generating $@..."
	@rm -rf $@
	@echo '/* Do not edit this file by hand */' >> $@
	@echo '/* It was generated by the build system */' >> $@
	@echo '#define XJUMP_VERSION "$(version)"' >> $@
	@echo '#define XJUMP_PREFIX  "$(prefix)"'  >> $@
	@echo '#define XJUMP_BINDIR  "$(bindir)"'  >> $@
	@echo '#define XJUMP_DATADIR "$(datadir)"' >> $@
	@echo '#define XJUMP_APP_ID  "$(app_id)"' >> $@
	@printf " done\n"

config.mk:
	@echo You must run ./configure before make
	@exit 1

misc/xjump.6.gz: misc/xjump.6
	gzip -c $< > $@
