#!/bin/sh
# Script for recompiling and running xjump in a single command.
# Intended for development

if ! [ -e config.mk ]; then
    echo >&2 "Please run ./configure first"
    exit 1
fi

install_output=$(make && make install) || exit $?
executable=$(echo "$install_output" | awk '/bin\/xjump/ { print $NF }')
"$executable" "$@"
