#!/bin/sh
# Script for recompiling and running xjump in a single command.
# Intended for development

if ! [ -e config.mk ]; then
    echo >&2 "Please run ./configure first"
    exit 1
fi

get_var() {
    grep "^$1 *=" config.mk | sed 's/[^=]*= *//'
}

prefix=$(get_var prefix)
bindir=$(get_var bindir)

eval prefix="$prefix"
eval bindir="$bindir"

make || exit $?
make install > /dev/null || exit $?
"$bindir"/xjump "$@"
